@startuml


actor "Game Organiser" as Organiser
actor Player

participant "Game Manager" as Manager
control Gateway
database "Game Session" as Game
queue Broker
participant "Web Display" as Web

activate Organiser


Organiser -> Gateway : Start session
activate Gateway

activate Broker

Gateway -> Game : Declare Game
activate Game
Gateway -> Broker : Declare namespace

Gateway --> Organiser : Admin Code

Organiser -> Manager : Run Game
activate Manager
Manager --> Organiser : Audience Code
Manager --> Gateway : Audience Code

Manager -> Gateway : Send Game Logic

Organiser -> Web : Join Game Admin Display
activate Web
Player --> Web : Join Game Audience Display

Web -> Broker : Subscribe
Organiser -> Player : Start
activate Player
Player -> Gateway : Initiate connection
Gateway -> Broker : Declare device

loop Game phase
    Organiser -> Gateway : Start Phase
    loop Player interactions
        Player -> Gateway : Interact
        Gateway -> Game : Update State
        Gateway -> Broker : Broadcast update
        Broker -> Web : Update Display
    end
    Organiser -> Gateway : End Phase
end
deactivate Player
Organiser -> Gateway : End Game
Gateway -> Game : Close Session
Gateway -> Broker : Release namespace
Broker -> Web : Display Game Stats
@enduml